export const ADD_PARTICIPANT = "ADD_PARTICIPANT";
export const ADD_JOIN_REQUEST = "ADD_JOIN_REQUEST";
export const SET_CALL_TITLE = "SET_CALL_TITLE";
export const SET_CALL_DESCRIPTION = "SET_CALL_DESCRIPTION";
export const SET_CALL_ID = "SET_CALL_ID";


